[project]
name = 'kathryn'

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ['B', 'D', 'E', 'F', 'N', 'RUF', 'Q', 'W', 'UP']

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ['F401']
"readme.md" = ['E501']
"tests/*.py" = ['D103']

[tool.ruff.lint.pydocstyle]
convention = 'numpy'

[tool.typos]
default.extend-ignore-words-re = ['ND']
